---
title: "Plot Kansas School District Cash Balances"
author: "Earl F Glynn<br>"
date: "<small>`r Sys.Date()`</small>"
output:
  html_document:
    code_download: true
    theme: cerulean
    toc: yes
    toc_depth:  3
    toc_float:
      collapsed:  yes
      smooth_scroll: yes
    number_sections: yes
    code_folding:  show
---

```{r setup, echo = FALSE}
# http://biostat.mc.vanderbilt.edu/wiki/Main/KnitrHtmlTemplate
require(Hmisc)    # provides knitrSet and other functions
knitrSet(lang = 'markdown',   # If using blogdown: knitrSet(lang='blogdown')
         fig.align = 'left',
         w = 6.5,
         h = 4.5,
         cache = FALSE)
```

`r hidingTOC(buttonLabel = "Outline")`

```{r startYourEngines, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  comment = NA)

time.1 <- Sys.time()
```

# Setup {.tabset .tabset-fade .tabset-pills}

## {.active}

## Constants

```{r Constants}
FILE_PREFIX   <- "x"    # no spaces
```

```{r}
EXCEL_LIMIT <- 2^20
```

## Packages

```{r Packages}
library(tidyverse)
```

Display formatting

```{r Display}
library(kableExtra)  # kable_styling
#library(IRdisplay)   # display_html (needed in Jupyter notebooks)
```

I/O

```{r IO}
library(readxl)      # read_xlsx
library(readr)       # write_csv
library(writexl)     # write_xlsx
```

 Graphics

```{r Graphics}
library(scales)      # comma, comma_format
```

```{r}
library(lubridate)
```


## ggplot theme

[ggplot Themes Gallery](https://www.datanovia.com/en/blog/ggplot-themes-gallery/)

```{r ggplotTheme}
theme_set(theme_minimal() +

          theme(axis.text             = element_text(size = 10),
                axis.title            = element_text(size = 14),

                plot.caption          = element_text(hjust = c(0.0,1.0)),
                plot.caption.position = "plot",   # R 4.0.0

                plot.title.position   = "plot",
                title                 = element_text(size = 14))
           )

COLOR_BAR     <- "skyblue"
COLOR_OUTLINE <- "grey80"
```

## Helper functions

```{r Helpers}
Show <- function(data, caption="", bigMark="",
                 height = NULL, width = NULL, ...)
{
  data                                       %>%
  kable("html", caption=caption,
        format.args=list(big.mark=bigMark))  %>%
  kable_styling(bootstrap_options=c("striped", "bordered", "condensed"),
                position="left",
                full_width=FALSE, ...)       %>%
  scroll_box(height = height, width = width)#%>%      # pixels
# as.character()                             %>%      # Jupyter Only
# display_html()                                      # Jupyter Only
}
```

# Year Cash Balances from School Districts


```{r}
districtsYears <- read_xlsx("Cash-Balances-by-School-District-LongFormat.xlsx",
                           guess_max = EXCEL_LIMIT)
dim(districtsYears)
```

```{r}
districtsYears  %>%  head(3)  %>%  Show(bigMark = ",")
```


```{r}
CAPTION <- "Source:  KSDE Data Central - Kansas Education Reports"
stamp   <- paste("watchdoglab.substack.com  efg", format(Sys.time(), "%Y-%m-%d"))
```


```{r CashBalanceByDistict, fig.width = 12, fig.height = 6}
 ggplot()                                 + 
  
  geom_line(data = districtsYears,
            aes(x = SchoolYear, 
                y = `Cash Balance`, 
                group = District),
            color = "grey")               +
  scale_y_log10(breaks = 10^(4:8),
                labels = scales::label_dollar())  +
  labs(title = "Kansas Unified School District Budget Summmary - Cash Balances",
       subtitle = "KSDE Comparative Performance and Fiscal System",
       x = "School Year",
       y = "Cash Balance [$]",
       caption = c(CAPTION, stamp))       +    
    geom_vline(xintercept = c(
                               3 - (182 - 118)/365,   # Sebelius end/Parkinson start
                               5 - (182  - 10)/365
                             ),
               color = "black",
               linetype = "solid", 
               size = 1.5)
  

```

Terms of Office:

```

* Kathleen Sebelius, Jan 13, 2003   - April 28, 2009   DOY 13   118
* Mark Parkinson,    April 28, 2009 - Jan. 10, 2011              10
* Sam Brownback,     Jan. 10, 2011  - Jan. 31, 2018              31
* Jeff Colyer,       Jan. 31, 2018  - Jan. 14, 2019              14
* Laura Kelly,       Jan. 14, 2019  - present

July 1 DOY = 182
```


```{r}
yearSummary <- read_xlsx("Cash-Balance-Totals-and-Quantiles-by-School-Year-LongFormat.xlsx",
                         guess_max = EXCEL_LIMIT)
dim(yearSummary)
```

# Epilog {.tabset .tabset-fade .tabset-pills}

## {.active}

## Session Info

```{r devtoolsSessionInfo}
devtools::session_info()
```

</div>

```{r epilogDeltaTime, echo=FALSE}
time.2 <- Sys.time()
processingTime <- paste("Processing time:", sprintf("%.1f",
                        as.numeric(difftime(time.2,
                                            time.1, units="secs"))), "secs\n")
```

`r processingTime`
`r format(time.2, "%Y-%m-%d %H%M")`

